# Generated by Django 2.2.24 on 2023-10-09 22:06

from django.db import migrations
import phonenumbers


def normalize_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phone):
            flat.owner_pure_phone = f"+{phone.country_code}" \
                                    f"{phone.national_number}"
        else:
            flat.owner_pure_phone = 'Телефона с таким номером не существует'
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20231009_2320'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_number),
    ]
