# Generated by Django 2.2.24 on 2023-10-09 22:06

from django.db import migrations
import phonenumbers


def normalize_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phone):
            full_phone_number = phonenumbers.format_number(phone, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
            flat.owner_pure_phone = full_phone_number
        else:
            flat.owner_pure_phone = None
            print(f'Телефона с номером {phone} не существует')
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20231009_2320'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_number),
    ]
