# Generated by Django 2.2.24 on 2023-10-09 22:06

from django.db import migrations
import phonenumbers


def normalize_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone = flat.owners_phonenumber
        if phonenumbers.is_valid_number(phonenumbers.parse(phone, 'RU')):
            flat.owner_pure_phone = f"+{phonenumbers.parse(phone, 'RU').country_code}" \
                                    f"{phonenumbers.parse(phone, 'RU').national_number}"
        else:
            flat.owner_pure_phone = 'Телефона с таким номером не существует'
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20231009_2320'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_number),
    ]
