# Generated by Django 2.2.24 on 2023-10-10 21:31

from django.db import migrations


def fill_owned_apartments(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(owner=flat.owner,
                                                     owners_phonenumber=flat.owners_phonenumber,
                                                     owner_pure_phone=flat.owner_pure_phone
                                                     )
        owner.owned_apartments.add(flat)
        # print(owner.owned_apartments)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20231010_2316'),
    ]

    operations = [
        migrations.RunPython(fill_owned_apartments),
        migrations.RemoveField(
            model_name='Flat',
            name='owner'
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owners_phonenumber'
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owner_pure_phone'
        )
    ]
