# Generated by Django 2.2.24 on 2023-10-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20231011_0321'),
        ('property', '0013_auto_20231011_0322'),
    ]

    operations = [
    ]
