# Generated by Django 2.2.24 on 2023-10-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_merge_20231011_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owned_by',
            field=models.ManyToManyField(related_name='flat_owners', to='property.Owner'),
        ),
    ]
