# Generated by Django 2.2.24 on 2023-10-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_flat_owned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owned_by',
        ),
    ]
