# Generated by Django 2.2.24 on 2023-10-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20231012_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owned_apartments',
            new_name='apartments',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
